    - name: app setup
      include_role:
        name: common
        tasks_from: app_setup

    - name: nodejs setup
      include_role:
        name: common
        tasks_from: nodejs_setup

    - name: systemd_setup
      include_role:
        name: common
        tasks_from: systemd_setup
