- name: app setup from command
  include_role:
    name: common
    tasks_from: app_setup

- name: python setup from common
  include_role:
    name: common
    tasks_from: python_setup

- name: systemd setup from common
  include_role:
    name: common
    tasks_from: systemd_setup