- name: disable nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: installation nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started

- name: remove nginx default content
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/*

- name: download frontend code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: unziping frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove nginx default conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copy roboshop content into nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: check nginx config syntax
  ansible.builtin.command: nginx -t
  register: nginx_syntax_check
  ignore_errors: true

- name: fail if nginx config is invalid
  ansible.builtin.fail:
    msg: "Nginx configuration test failed. Check the error log above."
  when: nginx_syntax_check.rc != 0

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_syntax_check.rc == 0

