      - name: app setup
        include_role:
          name: common
          tasks_from: app_setup

      - name: nodejs setup
        include_role:
          name: common
          tasks_from: nodejs_setup  

      - name: copying mongo repo
        ansible.builtin.copy:
          src: mongo.repo
          dest: /etc/yum.repos.d/mongo.repo

      - name: installing mongodb cilent server
        ansible.builtin.package:
          name: mongodb-mongosh
          state: present
          
      - name: Check if catalogue DB exists
        ansible.builtin.command: >
          mongosh --host mongodb.tcloudguru.in --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
        register: catalogue_db

      - name: Load products if catalogue DB does not exist
        ansible.builtin.shell: mongosh --host mongodb.tcloudguru.in < /app/db/master-data.js
        when: catalogue_db.stdout | int < 0

      - name: systemd_setup
        include_role:
          name: common
          tasks_from: systemd_setup