      - name: disabling nodejs module
        ansible.builtin.command: dnf module disable nodejs -y

      - name: enabling nodejs-20
        ansible.builtin.command: dnf module enable nodejs:20 -y

      - name: install nodejs 
        ansible.builtin.dnf:
          name: nodejs
          state: present
          
      - name: install npm dependencies
        community.general.npm:
          path: /app