      - name: copying catalogue service dependencies
        ansible.builtin.template:
          src: catalogue.service.j2
          dest: /etc/systemd/system/catalogue.service

      - name: systemctl daemon reload
        ansible.builtin.systemd_service:
          daemon-reload: true

      - name: restart catalogue
        ansible.builtin.service:
          name: catalogue
          enabled: true
          state: restarted